### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by letaylor** [wtsi-hgi/yascp#1]
Hi @maxozo, 

Henry Taylor and I do not want to be responsible for maintaining the code in this repo. We think it would be best to clean up the code in the bin by remove the below statements from all code. 

- [x] Remove `__author__ = 'Leland Taylor'` from all code
- [x] Remove  `__author__ = 'Henry Taylor'` from all code

**Comment by maxozo** [comment]
Have removed all the author affiliations in individual codes since they are in the README.md and have reset the history of these.
